name: rl_playground
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - glew=2.1.0
  - glib=2.68.4
  - pip=21.0
  - python=3.9.0
  - pip:
    - dm-control==1.0.20
    - dotmap==1.3.30
    - Cython==0.29.37
    - flax==0.8.4
    - gymnasium==1.0.0a2
    - hydra-core==1.3.2
    - imageio==2.33.1
    - jax==0.4.25
    - jaxlib==0.4.25
    - jaxopt==0.8.3
    - matplotlib==3.9.0
    - mujoco==3.1.6
    - mujoco-py==2.1.2.14
    - numpy==1.24.1
    - omegaconf==2.3.0
    - optax==0.2.2
    - pandas==2.1.4
    - Shimmy==2.0.0
    - tensorflow-probability==0.24.0
    - termcolor==2.4.0
    - tqdm==4.66.1
    - wandb==0.16.6
